//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnionManager.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Relation
    {
        public long Id { get; set; }
        public long TradeId { get; set; }
        public long UserId { get; set; }
        public Nullable<long> VehicleId { get; set; }
        public string Status { get; set; }
    
        public virtual Trade Trade { get; set; }
        public virtual User User { get; set; }
        public virtual Vehicle Vehicle { get; set; }
    }
}
