//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnionManager.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehicle
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vehicle()
        {
            this.Relations = new HashSet<Relation>();
        }
    
        public long Id { get; set; }
        public string NumberPlates { get; set; }
        public string Model { get; set; }
        public long ColorId { get; set; }
        public string VINName { get; set; }
        public bool IsHybrid { get; set; }
        public string Status { get; set; }
        public long VehicleGroupId { get; set; }
    
        public virtual Color Color { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Relation> Relations { get; set; }
        public virtual VehicleGroup VehicleGroup { get; set; }
    }
}
